### ISSUE TITLE
Scheduling doesn’t start until following week

### ISSUE THREAD

**Issue by WBWBW** [ianperrin/MMM-ModuleScheduler#17] opened 2018-08-31 00:46 UTC
I have a module scheduled with the following:
```javascript
module_schedule: {from: '50 10 * * *', to: '0 11 * * *' },
```
Let’s say it’s 8/5 10:45am (Saturday). The module will not show at 10:50am and the logs shows this:
```
MMM-ModuleScheduler is scheduling MMM-MyWastePickup using "50 10 * * *" and "0 11 * * *" with dim level undefined
MMM-ModuleScheduler is hiding MMM-MyWastePickup
MMM-ModuleScheduler has scheduled MMM-MyWastePickup
MMM-ModuleScheduler will next show MMM-MyWastePickup at Fri Aug 31 2018 10:50:00 GMT-0700 (PDT)
MMM-ModuleScheduler will next hide MMM-MyWastePickup at Fri Aug 31 2018 11:00:00 GMT-0700 (PDT)
```
It doesn’t get scheduled until the following Friday. 

If I set up a schedule for:
```javascript
module_schedule: {from: '0 8 * * SAT', to: '0 11 * * MON' },
```
Then it will be scheduled for the following Saturday but not today 8/25:
```
MMM-ModuleScheduler will next show MMM-MyWastePickup at Sat Sep 01 2018 08:00:00 GMT-0700 (PDT)
MMM-ModuleScheduler will next hide MMM-MyWastePickup at Mon Sep 03 2018 11:00:00 GMT-0700 (PDT)
```
If I schedule to for Monday, then it will be scheduled for the following Monday 9/3 but not 8/27:
```
MMM-ModuleScheduler is scheduling MMM-MyWastePickup using "0 8 * * MON" and "0 11 * * MON" with dim level undefined
MMM-ModuleScheduler is hiding MMM-MyWastePickup
MMM-ModuleScheduler has scheduled MMM-MyWastePickup
MMM-ModuleScheduler will next show MMM-MyWastePickup at Mon Sep 03 2018 08:00:00 GMT-0700 (PDT)
MMM-ModuleScheduler will next hide MMM-MyWastePickup at Mon Sep 03 2018 11:00:00 GMT-0700 (PDT)
```

Doesn’t matter what I day or time I select, it always gets scheduled a week later. I have the correct time zone set up. Time/date shows correctly. Other system Cron jobs start correctly.

**Comment by ianperrin** [comment] 2021-04-06 13:56
I was unable to reproduce this error and as it has been some time since it was reported I am going to close the issue. 

If you are still experiencing the error, please do re-open the issue. Thanks

**Closed as completed by ianperrin** 2021-04-06 13:56 UTC
